version: 2
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  earlymorning:
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
jobs:

  ##############
  # Build job uses a go cli tool to create a github release
  ##############
  build:

    working_directory: ~/kgrid

    docker:
    - image: circleci/openjdk:8u171-jdk-node

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      #must run install to ensure multi module dependencies(shelf-api) are cached
      - run: mvn -DskipTests clean install -pl application dependency:resolve-plugins dependency:go-offline -s .circleci/settings.xml

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

     # Release adds a Release to GitHub based on the tag via github api
      - run:
          name: Release
          command: |

            if [ $RELEASE ]; then
                .circleci/release.sh
            fi

      # save test results
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: application/target

      - persist_to_workspace:
          root: . # Persist current working directory
          paths: ./* # Glob. Will persist everything in folder

  deploy:

    docker:
      - image: circleci/openjdk:8u171-jdk-node

    steps:

      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy/Release
          command: |
               mkdir application/shelf
               mvn package -s .circleci/settings.xml
               HEROKU_API_KEY=$HEROKU_API_KEY mvn clean heroku:deploy -s .circleci/settings.xml -pl application

      # Create a shelf with KOs
      - run:
          name: Create Heroku Shelf
          command: |
            .circleci/create_shelf.sh https://kgrid-library.herokuapp.com/kos "ipp-collection"
            .circleci/create_shelf.sh https://kgrid-library.herokuapp.com/kos "cpic-collection"
            .circleci/create_shelf.sh https://kgrid-library.herokuapp.com/kos "opioid-collection example-collection cancer-risk-collection icon-array script-numerate postpci labwise"
          no_output_timeout: 5m
